event_inherited();
collectvanish = false;
collectboxid = -4;
in_the_void = false;
image_alpha = 0.35;
escape = 1;
image_speed = 0.35;
sprite_index = spr_collectescapePZ;
image_index = 0;
use_palette = false;
gotowardsPlayer = false;
movespeed = 0;
sound = frogdeath3;
