draw_set_halign(fa_center);
draw_set_font(global.font);
draw_option(150, 30 + ScrollY, "BACK", optionselected == video_selected.back);
draw_option(480, 100 + ScrollY, "WINDOW MODE", optionselected == video_selected.fullscreen);
draw_option(280, 150 + ScrollY, "WINDOWED", !optionsaved_fullscreen);
draw_option(680, 150 + ScrollY, "FULLSCREEN", optionsaved_fullscreen);
draw_option(480, 200 + ScrollY, "RESOLUTION", optionselected == video_selected.resolution);
draw_option(250, 250 + ScrollY, "480X260", optionsaved_resolution == 0);
draw_option(480, 250 + ScrollY, "960X540", optionsaved_resolution == 1);
draw_option(710, 250 + ScrollY, "1280X720", optionsaved_resolution == 2);
draw_option(480, 300 + ScrollY, "SMOOTH CAM", optionselected == video_selected.smoothcam);
draw_option(380, 350 + ScrollY, "ON", optionsaved_smoothcam);
draw_option(580, 350 + ScrollY, "OFF", !optionsaved_smoothcam);
draw_option(480, 400 + ScrollY, "SCREEN TILT", optionselected == video_selected.screentilt);
draw_option(380, 450 + ScrollY, "ON", optionsaved_screentilt);
draw_option(580, 450 + ScrollY, "OFF", !optionsaved_screentilt);
draw_option(480, 500 + ScrollY, "SHOWHUD", optionselected == video_selected.hud_visible);
draw_option(380, 550 + ScrollY, "ON", optionsaved_showhud);
draw_option(580, 550 + ScrollY, "OFF", !optionsaved_showhud);
draw_option(480, 600 + ScrollY, "TIMER", optionselected == video_selected.timer_enable);
draw_option(380, 650 + ScrollY, "ON", optionsaved_timer);
draw_option(580, 650 + ScrollY, "OFF", !optionsaved_timer);
draw_option(480, 700 + ScrollY, "TIMER TYPE", optionselected == video_selected.timer_type);
draw_option(275, 750 + ScrollY, "PER LEVEL", optionsaved_timertype == 0);
draw_option(565, 750 + ScrollY, "PER SAVE", optionsaved_timertype == 1);
draw_option(785, 750 + ScrollY, "BOTH", optionsaved_timertype == 2);
draw_set_font(global.smallfont);
draw_text(480, 512, subtitle);
