wavetext = wave(4, -4, 3, 0);
draw_set_color(c_black);
draw_set_alpha(darkalpha);
draw_rectangle(-32, -32, 992, 572, false);
draw_set_font(global.newfont);
draw_set_halign(fa_center);
draw_set_color(c_white);
draw_set_alpha(iconalpha);
draw_sprite(spr_oldlevel, !selected, 0, 0);
draw_sprite(spr_newlevel, selected, 0, 0);
draw_text_color(480, 100 + wavetext, "Choose Level Layout", c_white, c_white, c_white, c_white, iconalpha);
draw_set_halign(fa_center);
draw_set_alpha(1);
